services:
  db_curs:
    container_name: db_curs
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bobskyNIGGER
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    image: postgres:14.3-alpine
